CREATE SCHEMA  if not exists DBADDRESS;

use DBADDRESS;

-- Address
insert into TB_ADDRESS (ID_ADDRESS, ZIPCODE, CITY, NEIGHBORHOOD, STATE)
values (1, '72954023', 'BRASILIA', 'ASA SUL', 'DF');
insert into TB_ADDRESS (ID_ADDRESS, ZIPCODE, CITY, NEIGHBORHOOD, STATE)
values (2, '71005698', 'GAMA', 'SETOR SUL', 'DF');
insert into TB_ADDRESS (ID_ADDRESS, ZIPCODE, CITY, NEIGHBORHOOD, STATE)
values (3, '70582695', 'SOBRADINHO', 'AREAL 2', 'DF');
insert into TB_ADDRESS (ID_ADDRESS, ZIPCODE, CITY, NEIGHBORHOOD, STATE)
values (4, '50454114', 'PRADO', 'PORTAL DAS ABELHAS', 'BA');
insert into TB_ADDRESS (ID_ADDRESS, ZIPCODE, CITY, NEIGHBORHOOD, STATE)
values (5, '96321458', 'PAULO', 'AUGUSTA MELO', 'SP');