CREATE TABLE IF NOT EXISTS  TB_ADDRESS
(
    ID_ADDRESS   BIGINT UNSIGNED AUTO_INCREMENT,
    ZIPCODE      VARCHAR(13) NOT NULL,
    CITY         VARCHAR(40) NOT NULL,
    NEIGHBORHOOD VARCHAR(70),
    STATE        VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID_ADDRESS)
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8;